export const seedData = {
  customers: [
    {
      id: 'c-1',
      name: 'Acme Holdings',
      industry: 'FMCG',
      contact: 'Sara Lim',
      email: 'sara@acme.co',
      phone: '+855 12 345 678',
      address: '#42, St. 271, Toul Tom Poung, Phnom Penh',
      vatTin: 'K001-901234567',
      stage: 'Active',
      staff: [
        { id: 'st-1', name: 'Sara Lim', role: 'CEO', department: 'Executive', email: 'sara@acme.co', phone: '+855 12 345 678', reportsTo: null },
        { id: 'st-2', name: 'Vichet Khoeun', role: 'CFO', department: 'Finance', email: 'vichet@acme.co', phone: '', reportsTo: 'st-1' },
        { id: 'st-3', name: 'Nita Som', role: 'Head of Marketing', department: 'Marketing', email: 'nita@acme.co', phone: '', reportsTo: 'st-1' },
        { id: 'st-4', name: 'Pisey Touch', role: 'Brand Manager', department: 'Marketing', email: '', phone: '', reportsTo: 'st-3' },
      ],
      productLinks: [
        { id: 'pl-1', productId: 'p-webill365', linkedAt: '2026-04-10T08:00:00.000Z' },
      ],
      taskGroups: [
        { id: 'tg-1', name: 'Q2 Campaign' },
        { id: 'tg-2', name: 'Account Ops' },
      ],
      tasks: [
        {
          id: 't-1',
          name: 'Q2 campaign brief review',
          registerDate: '2026-04-20',
          description: 'Review draft brief and consolidate feedback from creative + media leads.',
          status: 'In Progress',
          file: null,
          due: '2026-05-02',
          assignee: 'Sara Lim',
          groupId: 'tg-1',
        },
        {
          id: 't-2',
          name: 'Send proposal v3',
          registerDate: '2026-04-15',
          description: 'Updated pricing table and add scope-out items per last call.',
          status: 'Done',
          file: null,
          due: '2026-04-28',
          assignee: 'You',
          groupId: 'tg-2',
        },
      ],
      logs: [
        {
          id: 'log-c1-1',
          ts: '2026-04-22T10:00:00.000Z',
          type: 'activity',
          message: 'Meeting',
          meta: { activityType: 'Meeting', note: 'Aligned on KPIs and budget cap.', date: '2026-04-22' },
        },
        {
          id: 'log-c1-2',
          ts: '2026-04-15T08:00:00.000Z',
          type: 'customer.create',
          message: 'Customer created',
          meta: { name: 'Acme Holdings' },
        },
      ],
      files: [
        {
          id: 'f-1',
          name: 'MSA 2026.pdf',
          description: 'Signed · $48,000 · Renews 2027-01-15',
          type: 'application/pdf',
          size: 0,
          uploadedAt: '2026-04-15T10:00:00.000Z',
          dataUrl: null,
        },
      ],
    },
    {
      id: 'c-2',
      name: 'BlueWave Bank',
      industry: 'Finance',
      contact: 'Dara Pich',
      email: 'dara@bluewave.kh',
      phone: '+855 99 887 766',
      address: '',
      vatTin: '',
      stage: 'Prospect',
      staff: [],
      productLinks: [],
      taskGroups: [],
      tasks: [
        {
          id: 't-3',
          name: 'Schedule pitch deck walkthrough',
          registerDate: '2026-04-22',
          description: '',
          status: 'Todo',
          file: null,
          due: '2026-04-30',
          assignee: 'You',
          groupId: null,
        },
      ],
      logs: [
        {
          id: 'log-c2-1',
          ts: '2026-04-22T08:00:00.000Z',
          type: 'customer.create',
          message: 'Customer created',
          meta: { name: 'BlueWave Bank' },
        },
      ],
      files: [],
    },
  ],
  products: [
    {
      id: 'p-webill365',
      name: 'WeBill365',
      type: 'Product',
      price: 0,
      income: [
        {
          id: 'i-1',
          date: '2026-04-10',
          invoiceNo: 'INV-2026-001',
          customerNo: 'C-001',
          customerName: 'Acme Holdings',
          source: 'Acme Holdings',
          customerId: 'c-1',
          items: [
            { id: 'li-1a', description: 'WeBill365 — Annual license', qty: 1, unitPrice: 4090.91, total: 4090.91 },
          ],
          taxRate: 0.1,
          subtotal: 4090.91,
          tax: 409.09,
          grandTotal: 4500,
          amount: 4500,
          note: 'Deposit invoice',
        },
      ],
      expenses: [],
      assets: [
        { id: 'd-1', name: 'WeBill365 — Sales Deck v4', type: 'Slide', link: '#' },
      ],
    },
    { id: 'p-wabooks',      name: 'WABOOKS',      type: 'Product', price: 0, income: [], expenses: [], assets: [] },
    { id: 'p-weums365',     name: 'WeUMS365',     type: 'Product', price: 0, income: [], expenses: [], assets: [] },
    { id: 'p-weloan',       name: 'WeLoan',       type: 'Product', price: 0, income: [], expenses: [], assets: [] },
    { id: 'p-weinvoice365', name: 'WeInvoice365', type: 'Product', price: 0, income: [], expenses: [], assets: [] },
    { id: 'p-morningmate',  name: 'Morningmate',  type: 'Product', price: 0, income: [], expenses: [], assets: [] },
    { id: 's-smsi',         name: 'SM/SI',        type: 'Service', price: 0, income: [], expenses: [], assets: [] },
    { id: 's-outsourcing',  name: 'Outsourcing',  type: 'Service', price: 0, income: [], expenses: [], assets: [] },
  ],
  partners: [
    {
      id: 'pa-1',
      name: 'Vannak Sok',
      company: 'Pixel Studio',
      role: 'Creative Director',
      email: 'vannak@pixel.studio',
      phone: '+855 70 123 456',
      tasks: [
        {
          id: 'pt-1',
          name: 'Confirm video shoot date',
          setDate: '2026-04-22',
          description: 'Pick a slot that works for both production and brand teams.',
          expense: 0,
          file: null,
          due: '2026-05-05',
          done: false,
        },
        {
          id: 'pt-2',
          name: 'Pay deposit for Q2 video shoot',
          setDate: '2026-04-25',
          description: '50% deposit before pre-production lock.',
          expense: 1500,
          file: null,
          due: '2026-04-30',
          done: false,
        },
      ],
      activities: [
        { id: 'pa-act-1', date: '2026-04-20', type: 'Call', note: 'Negotiated production rate.' },
      ],
    },
  ],
  assets: [
    { id: 'as-1', name: 'MacBook Pro 14"', category: 'Hardware', assignee: 'Sales Lead', serial: 'C02XJ', status: 'In use' },
    { id: 'as-2', name: 'HubSpot Sales Hub', category: 'Software', assignee: 'BD Team', serial: '—', status: 'Active' },
    { id: 'as-3', name: 'Booth Banner Stand', category: 'Marketing', assignee: 'Events', serial: 'BNR-09', status: 'Storage' },
  ],
  campaigns: [
    {
      id: 'cm-1',
      name: 'WeBill365 — Q2 launch push',
      description: 'Awareness sprint targeting SME bookkeepers ahead of the Q2 invoicing season.',
      productId: 'p-webill365',
      startDate: '2026-04-15',
      endDate: '2026-06-30',
      status: 'Active',
      todos: [
        {
          id: 'cmt-1',
          postDate: '2026-04-25',
          concept: 'Founder story — why we built WeBill365',
          type: 'Reel',
          channel: 'Instagram',
          keyFeature: 'Founder POV authenticity',
          caption: 'From burnt-out finance team to one-tap invoicing 🚀 The story behind WeBill365.',
          artwork: null,
        },
        {
          id: 'cmt-2',
          postDate: '2026-05-02',
          concept: 'Product demo — invoice in 30 seconds',
          type: 'Video',
          channel: 'TikTok',
          keyFeature: 'Speed of invoicing flow',
          caption: 'Pay your team faster. Watch us send a real invoice in under 30 seconds with WeBill365.',
          artwork: null,
        },
      ],
    },
  ],
}
